Connect to the latest version of the data service API. (#48)
Resolved Issues

- Fixed build error TS2339: Property 'env' does not exist on type 'ImportMeta'.
- Fixed the issue where `browser.i18n.getMessage` did not work on Safari.

Miscellaneous

- Connect to the latest version of the data service API v24.
- Link popup version text to the home site.
- Bump version from 24.6.2 to 24.9.30.